project:
  type: website
  output-dir: docs

website:
  title: "schools-analysis"
  navbar:
    left:
      - href: index.qmd
        text: Spanish
      - href: English.qmd
        text: English
      - href: Code.qmd
        text: Code

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



